[pytest]
addopts = -v -s --alluredir=allure-results --clean-alluredir
testpaths = lesson_10
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: Smoke tests
    purchase: Purchase flow tests
    calculator: Calculator tests
    slow: Slow tests